# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

obj_fun <- function(A, U2) {
    .Call(`_codco_obj_fun`, A, U2)
}

remove_one <- function(A, i, u) {
    .Call(`_codco_remove_one`, A, i, u)
}

remove_one_mat <- function(A, i) {
    .Call(`_codco_remove_one_mat`, A, i)
}

add_one <- function(A, sigma_jj, f, u) {
    .Call(`_codco_add_one`, A, sigma_jj, f, u)
}

add_one_mat <- function(A, sigma_jj, f) {
    .Call(`_codco_add_one_mat`, A, sigma_jj, f)
}

ChooseSwap <- function(idx_in, A, sig, u, out2, out3) {
    .Call(`_codco_ChooseSwap`, idx_in, A, sig, u, out2, out3)
}

Grad <- function(idx_in, A, sig, u, tol = 1e-9, trace = TRUE) {
    .Call(`_codco_Grad`, idx_in, A, sig, u, tol, trace)
}

ChooseSwapRobust <- function(nlist, idx_in, A_list, sig_list, u_list, weights, out2, out3) {
    .Call(`_codco_ChooseSwapRobust`, nlist, idx_in, A_list, sig_list, u_list, weights, out2, out3)
}

GradRobust <- function(nlist, idx_in, A_list, sig_list, u_list, weights, tol = 1e-9, trace = TRUE) {
    .Call(`_codco_GradRobust`, nlist, idx_in, A_list, sig_list, u_list, weights, tol, trace)
}

rcpparma_hello_world <- function() {
    .Call(`_codco_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_codco_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_codco_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_codco_rcpparma_bothproducts`, x)
}

